name       : kalendar
version    : 23.04.1
release    : 9
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.1/src/kalendar-23.04.1.tar.xz : 773876ae51bd6ce6e0011742dcf509b6b1ab34afc0ec9e3f1f2032e56a76aab0
homepage   : https://apps.kde.org/kalendar/
license    :
    - BSD-2-Clause
    - BSD-3-Clause
    - CC0-1.0
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
    - LGPL-3.0-or-later
    - GPL-2.0-or-later
    - GPL-3.0-or-later
component  : desktop.kde
summary    : A calendar application using Akonadi to sync with external services
description: |
    A calendar application using Akonadi to sync with external services
builddeps  :
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Location)
    - pkgconfig(Qt5QuickControls2)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebEngineWidgets)
    - akonadi-contacts-devel
    - akonadi-calendar-devel
    - calendarsupport-devel
    - eventviews-devel
    - gpgme-qt-devel
    - kcontacts-devel
    - kdbusaddons-devel
    - kdepim-runtime
    - kidentitymanagement-devel
    - kmime-devel
    - kiconthemes-devel
    - kio-devel
    - kirigami-addons-devel
    - kirigami2-devel
    - ktextaddons-devel
    - mailcommon-devel
    - pimcommon-devel
    - qqc2-desktop-style-devel
rundeps    :
    - kdepim-runtime
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
