name       : kalendar
version    : 22.08.3
release    : 6
source     :
    - https://cdn.download.kde.org/stable/release-service/22.08.3/src/kalendar-22.08.3.tar.xz : 8c7c07a422323a586b87dd578afd9696a5bb13bcd3fc5966a4c239321ef1a7a0
homepage   : https://apps.kde.org/kalendar/
license    :
    - BSD-2-Clause
    - BSD-3-Clause
    - CC0-1.0
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
    - LGPL-3.0-or-later
    - GPL-2.0-or-later
    - GPL-3.0-or-later
component  : desktop.kde
summary    : A calendar application using Akonadi to sync with external services
description: |
    A calendar application using Akonadi to sync with external services
builddeps  :
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Location)
    - pkgconfig(Qt5QuickControls2)
    - pkgconfig(Qt5Svg)
    - akonadi-contacts-devel
    - akonadi-calendar-devel
    - calendarsupport-devel
    - eventviews-devel
    - kcontacts-devel
    - kdbusaddons-devel
    - kdepim-runtime
    - kidentitymanagement-devel
    - kmime-devel
    - kiconthemes-devel
    - kio-devel
    - kirigami2-devel
    - qqc2-desktop-style-devel
rundeps    :
    - kdepim-runtime
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
